// Public contract for the supplied dictionaries. No runtime dependency on JSON in domain.
export interface PortfolioCopy {
  readonly languageNames: {
    readonly es: string;
    readonly en: string;
    readonly pt: string;
  };
  readonly switchLanguage: {
    readonly es: string;
    readonly en: string;
    readonly pt: string;
  };
  readonly errors: {
    readonly notFound: string;
    readonly notFoundDescription: string;
    readonly generic: string;
    readonly retry: string;
  };
  readonly empty: {
    readonly projects: string;
    readonly experience: string;
    readonly results: string;
    readonly terminal: string;
    readonly links: string;
  };
  readonly form: {
    readonly name: string;
    readonly email: string;
    readonly subject: string;
    readonly message: string;
    readonly submit: string;
    readonly preparing: string;
    readonly required: string;
    readonly invalidEmail: string;
    readonly tooLong: string;
    readonly review: string;
    readonly unavailable: string;
    readonly privacy: string;
  };
  readonly terminalResults: {
    readonly help: string;
    readonly projects: string;
    readonly skills: string;
    readonly experience: string;
    readonly contact: string;
    readonly cleared: string;
    readonly outputLabel: string;
  };
  readonly a11y: {
    readonly projectStatus: string;
    readonly downloadCv: string;
    readonly externalLink: string;
    readonly projectImage: string;
    readonly commandRoom: string;
  };
  readonly seo: {
    readonly home: string;
    readonly experience: string;
    readonly projects: string;
    readonly projectDetail: string;
    readonly skills: string;
    readonly recruiter: string;
    readonly contact: string;
    readonly notFound: string;
  };
  readonly navigationLabel: string;
  readonly languageSelector: string;
  readonly closeMenu: string;
  readonly nav: readonly string[];
  readonly role: string;
  readonly station: string;
  readonly headline: readonly string[];
  readonly intro: string;
  readonly projects: string;
  readonly cv: string;
  readonly recruiter: string;
  readonly tech: string;
  readonly featured: string;
  readonly all: string;
  readonly finance: string;
  readonly pos: string;
  readonly live: string;
  readonly building: string;
  readonly financeDesc: string;
  readonly posDesc: string;
  readonly connect: string;
  readonly motto: string;
  readonly footer: string;
  readonly close: string;
  readonly back: string;
  readonly quick: string;
  readonly quickDesc: string;
  readonly quickTitle: string;
  readonly experienceTitle: string;
  readonly experienceIntro: string;
  readonly now: string;
  readonly jobs: readonly {
    readonly role: string;
    readonly employer: string;
    readonly location: string;
    readonly period: string;
    readonly summary: string;
    readonly roles: readonly { readonly role: string; readonly period: string }[];
  }[];
  readonly journey: string;
  readonly progression: string;
  readonly years: string;
  readonly stack: string;
  readonly fullHistory: string;
  readonly educationList: readonly string[];
  readonly projectsTitle: string;
  readonly projectsIntro: string;
  readonly details: string;
  readonly projectRole: string;
  readonly architect: string;
  readonly architectPos: string;
  readonly context: string;
  readonly financeDetail: string;
  readonly posDetail: string;
  readonly decisions: string;
  readonly posDecisions: readonly string[];
  readonly financeDecisions: readonly string[];
  readonly financeNote: string;
  readonly backToProjects: string;
  readonly demo: string;
  readonly repository: string;
  readonly decisionsNote: string;
  readonly links: string;
  readonly architectureDetail: string;
  readonly skillsTitle: string;
  readonly skillsIntro: string;
  readonly skillLabels: readonly string[];
  readonly terminalTitle: string;
  readonly terminalHelp: string;
  readonly terminalUnknown: string;
  readonly terminalLabel: string;
  readonly terminalClear: string;
  readonly send: string;
  readonly contactTitle: string;
  readonly contactIntro: string;
  readonly email: string;
  readonly location: string;
  readonly socialPending: string;
  readonly socialNote: string;
  readonly contactEmail: string;
  readonly mailSubject: string;
  readonly education: string;
  readonly educationText: string;
  readonly languages: string;
  readonly languageText: string;
  readonly download: string;
  readonly menu: string;
  readonly skip: string;
  readonly progress: string;
  readonly progressNote: string;
  readonly screen: string;
  readonly summary: string;
  readonly pending: string;
  readonly original: string;
  readonly diagram: string;
  readonly financeTag: string;
  readonly next: string;
  readonly completed: string;
}
